DROP TABLE IF EXISTS proveedor;
CREATE TABLE proveedor(
	pk_proveedor	INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	pagina_web		VARCHAR(50),
	pais			VARCHAR(50),
	ciudad			VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);