DROP TABLE IF EXISTS marca;
CREATE TABLE marca(
	pk_marca		INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombre			VARCHAR(50),
	pais			VARCHAR(50),
	pagina_web		VARCHAR(50),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);